//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ETicaretDemo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kategori
    {
        public int id { get; set; }
        public string Baslik { get; set; }
        public int UstKategori { get; set; }
        public bool isActive { get; set; }
    }
}
